### ISSUE TITLE
Bifrost tests fail

### ISSUE THREAD

**Issue by nithyanandan** [nithyanandan/EPIC#20]
```
(EPIC-dev) t_nithyanandan@intrepid:/data3/t_nithyanandan/codes/others/python/Bifrost/JamesKent$ make test
#make -C src test
cd test && ./download_test_data.sh ; python -m unittest discover
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3929k  100 3929k    0     0  4380k      0 --:--:-- --:--:-- --:--:-- 4400k
mv: cannot move 'for_test_suite' to 'data/for_test_suite': Directory not empty
WARNING: Install simplejson for better performance
WARNING: Install simplejson for better performance
WARNING: Install simplejson for better performance
..........................................rm: cannot remove '/dev/shm/bifrost/142615/SaveOp/perf': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/SaveOp/sequence0': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/SaveOp/bind': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/SaveOp/size': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/SaveOp/in': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/perf': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/sequence0': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/bind': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/size': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/out': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/in': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/perf': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/sequence0': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/bind': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/size': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/out': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/in': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/perf': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/sequence0': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/bind': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/size': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/out': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/in': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/OfflineCaptureOp/perf': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/OfflineCaptureOp/size': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/OfflineCaptureOp/bind': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/OfflineCaptureOp/out': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/rings/gridandfft': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/rings/transpose': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/rings/fengine': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/rings/capture': Permission denied
.....#### DIFFERENCE: 0.104001 ####
E.....s...........................................................................................................................................s.............s..............F.................
======================================================================
ERROR: test_ntime_1024_nchan2_npol2_gridsize256_illumsize10_datasize256 (test_romein.RomeinTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_romein.py", line 132, in test_ntime_1024_nchan2_npol2_gridsize256_illumsize10_datasize256
    self.run_test(grid_size=256, illum_size=10, data_size=256, ntime=1024, npol=2, nchan=2)
  File "test_romein.py", line 117, in run_test
    raise ValueError("Large difference between naive romein and CUDA implementation.")
ValueError: Large difference between naive romein and CUDA implementation.

======================================================================
FAIL: test_read_write (test_binary_io.BinaryIOTest)
Read from a binary file, then write to another one
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_binary_io.py", line 82, in test_read_write
    np.testing.assert_almost_equal(self.s1, outdata1)
  File "/data3/t_nithyanandan/src/anaconda/envs/EPIC-dev/lib/python2.7/site-packages/numpy/testing/utils.py", line 573, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/data3/t_nithyanandan/src/anaconda/envs/EPIC-dev/lib/python2.7/site-packages/numpy/testing/utils.py", line 979, in assert_array_almost_equal
    precision=decimal)
  File "/data3/t_nithyanandan/src/anaconda/envs/EPIC-dev/lib/python2.7/site-packages/numpy/testing/utils.py", line 747, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(shapes (33554432,), (33292288,) mismatch)
 x: array([ 0.       ,  0.0399893,  0.0799147, ...,  0.7024202,  0.7856785,
        0.7856785], dtype=float32)
 y: array([ 0.       ,  0.0399893,  0.0799147, ...,  0.9955596,  0.9760557,
        0.9760557], dtype=float32)

----------------------------------------------------------------------
Ran 240 tests in 1001.039s

FAILED (failures=1, errors=1, skipped=3)
rm: cannot remove '/dev/shm/bifrost/142615/SaveOp/perf': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/SaveOp/sequence0': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/SaveOp/bind': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/SaveOp/size': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/SaveOp/in': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/perf': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/sequence0': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/bind': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/size': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/out': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/MOFFCorrelatorOp/in': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/perf': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/sequence0': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/bind': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/size': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/out': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/TransposeOp/in': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/perf': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/sequence0': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/bind': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/size': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/out': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/FDomainOp/in': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/OfflineCaptureOp/perf': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/OfflineCaptureOp/size': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/OfflineCaptureOp/bind': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/OfflineCaptureOp/out': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/rings/gridandfft': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/rings/transpose': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/rings/fengine': Permission denied
rm: cannot remove '/dev/shm/bifrost/142615/rings/capture': Permission denied
Makefile:19: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by adampbeardsley** [comment]
This looks like the errors we get when we do user installs but don't copy over Jayce's `proclog.cpp` file. Did you copy that over before running the `make` commands?

**Comment by jaycedowell** [comment]
The `proclog.cpp` thing usually leads to ring-related errors.  The two errors/failures here look to be something different.  Both are accuracy errors, though, one from romein and one from binaryio.  I may have seen the romein one before but not the io one.

**Comment by adampbeardsley** [comment]
Oh sorry, I just saw all the permission denieds. I got the io error in NM, and I think the answer was that two of us were running at the same time. I don't think anyone's running now though...

**Comment by jaycedowell** [comment]
Oh, binaryio fails for me on intrepid as well.  I wonder what is causing that?

**Comment by jaycedowell** [comment]
I'm getting the same binaryio error on ADP as well.  It can probably be ignored.

I have no clue about the romein one.

**Comment by jaycedowell** [comment]
I also get the romein error on ADP.

**Comment by nithyanandan** [comment]
So these are not show-stoppers?

**Comment by jaycedowell** [comment]
I think so.

**Comment by KentJames** [comment]
No they should not be. I am fairly sure its just floating point error
thrown up in an extreme test case.

When I rebuild the romein back-end in bifrost I will build a proper
series of tests too,
